version: '3.8'

services:
  mysql:
    container_name: mysql_tfg
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_tienda
      MYSQL_USER: erwin
      MYSQL_PASSWORD: erwinpass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
